Adding new SMT
rentpath/kafka-connect-transforms pull request #14
Opened 2023-11-07 20:38 UTC by Kevinn09

[Card](https://rentgroup.atlassian.net/browse/SRV-5892)

2023-11-07 20:49 UTC, Kevinn09 commented on src/main/java/com/rentpath/kafka/connect/transforms/PopulateFieldTransform.java
> +public class PopulateFieldTransform<R extends ConnectRecord<R>> implements Transformation<R> {
Having some difficulty deciding on the transform name. We've been using the term "Coalesce" so I was thinking of using something like "CoalesceFieldsTransform" or "UnifyFieldsTransform", but it didn't feel exactly right because we aren't really combining or unifying fields together; it felt like we're more setting a field based on other fields. "PopulateFieldTransform" doesn't really fully capture what we're doing either so I'm not really set on it. Happy to take any feedback and name it whatever we think works best?

2023-11-14 15:43 UTC, awebneck requested changes
One small issue, otherwise looks good

2023-11-14 15:43 UTC, awebneck commented on src/main/java/com/rentpath/kafka/connect/transforms/PopulateFieldTransform.java
> +public class PopulateFieldTransform<R extends ConnectRecord<R>> implements Transformation<R> {
@Kevinn09 I still prefer `Coalesce`. The `COALESCE` SQL function from which I took the name serves the same purpose as this - given a list of values, it returns the first non-null value or null if all are null. `PopulateField` is too ambiguous

2023-11-14 15:43 UTC, awebneck commented on src/main/java/com/rentpath/kafka/connect/transforms/PopulateFieldTransform.java
> +                            outValue = inputRecord.get(contributorFieldName);
I don't see anywhere we're checking that the value is not null before breaking; if the contributor value is null, we should continue the loop until either the value is _not_ null or the loop is exhausted.

2023-11-15 14:31 UTC, merged